server:
  http_listen_port: 9080
  grpc_listen_port: 0
  # log_level: "warn"

positions:
  filename: /tmp/positions.yaml


clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

# local machine logs

  - job_name: local
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

# docker logs

  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

# syslog target

# - job_name: syslog
#   syslog:
#     listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#     idle_timeout: 60s
#     label_structured_data: yes
#     labels:
#       job: "syslog"
#   relabel_configs:
#     - source_labels: ['__syslog_message_hostname']
#       target_label: 'host'

# Taken from https://alexandre.deverteuil.net/post/syslog-relay-for-loki/
  # - job_name: syslog
  #   syslog:
  #     listen_address: 0.0.0.0:1514
  #     idle_timeout: 60s
  #     labels:
  #       job: syslog
  #   relabel_configs:
  #     - source_labels: [__syslog_message_hostname]
  #       target_label: host

# thank you chatgpt!
  - job_name: edge_router_syslog
    syslog:
      listen_address: 0.0.0.0:1514 # the address and port to listen for syslog messages
      idle_timeout: 60s # the timeout for idle connections
      label_structured_data: yes # whether to add structured data as labels
      labels: # static labels to add to every log entry
        job: "edge_router_syslog"
        ver: "1.4"
    pipeline_stages:
    - regex:
        # expression: '(?P<date>\w+ \d+ \d+:\d+:\d+) (?P<host>\w+) (?P<kernel>\w+) (?P<message_id>\w+): \[(?P<rule>\w+)\]IN=(?P<in>\w+) OUT=(?P<out>\w*) MAC=(?P<mac>[\w:]+) SRC=(?P<src>[\d.]+) DST=(?P<dst>[\d.]+) LEN=(?P<len>\d+) TOS=(?P<tos>[\w.]+) PREC=(?P<prec>[\w.]+) TTL=(?P<ttl>\d+) ID=(?P<id>\d+) PROTO=(?P<proto>\w+) SPT=(?P<spt>\d+) DPT=(?P<dpt>\d+) WINDOW=(?P<window>\d+) RES=(?P<res>[\w.]+) (?P<flags>[A-Z ]+) URGP=(?P<urgp>\d+)$'
        expression: '(?P<date>\w+ \d+ \d+:\d+:\d+) (?P<host>\b\w+-\w+-\w+-\w+-\w+\b) (?P<source>\w+)$'
    - labels:
        date:
        host:
        source:
        # priority:
        # version:
        # date:
        # router:
        # kernel:
        # message_id:
        # rule:
        # in:
        # out:
        # mac:
        # src:
        # dst:
        # len:
        # tos:
        # prec:
        # ttl:
        # id:
        # proto:
        # spt:
        # dpt:
        # window:
        # res:
        # flags:
        # urgp: 
    relabel_configs: # relabeling rules to apply to the log entries
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'
    - source_labels: ['__syslog_message_rule']
      target_label: 'rule'
    - source_labels: ['__syslog_message_source']
      target_label: 'source'
      


