server:
  http_listen_port: 9080
  grpc_listen_port: 0
  #log_level: "debug"

positions:
  filename: /tmp/positions.yaml


clients:
  # - url: http://loki:3100/loki/api/v1/push
  - url: https://11873:glc_eyJvIjoiNDU1MjYwIiwibiI6InN0YWNrLTE2MzkxOC1pbnRlZ3JhdGlvbi1yc3lzbG9nLWhvbWUiLCJrIjoiaTQzN0tkdjcxQno2dng5QW42MFdKUUUyIiwibSI6eyJyIjoidXMifX0=@logs-prod-us-central1.grafana.net/api/prom/push


scrape_configs:

# local machine logs

  - job_name: local
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

# docker logs

  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

# syslog target

# - job_name: syslog
#   syslog:
#     listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#     idle_timeout: 60s
#     label_structured_data: yes
#     labels:
#       job: "syslog"
#   relabel_configs:
#     - source_labels: ['__syslog_message_hostname']
#       target_label: 'host'

# Taken from https://alexandre.deverteuil.net/post/syslog-relay-for-loki/
  # - job_name: syslog
  #   syslog:
  #     listen_address: 0.0.0.0:1514
  #     idle_timeout: 60s
  #     labels:
  #       job: syslog
  #   relabel_configs:
  #     - source_labels: [__syslog_message_hostname]
  #       target_label: host

  - job_name: rsyslog
    # pipeline_stages:
    # - regex:
    #     # expression: '\[(?P<rule>.*)\](?P<all>.*)'
    #     expression: '\[(?P<rule>.*)\]IN=(?P<inport>\w*) OUT=(?P<outport>\w*) MAC=(?P<macaddress>[\w:]+) SRC=(?P<sourceip>[\d.]+) DST=(?P<destinationip>[\d.]+) LEN=(?P<length>\d+)'
    # - labels:
    #     rule:
    #     inport:
    #     outport:
    #     macaddress:
    #     sourceip:
    #     destinationip:
    #     length:
  
    syslog:
      listen_address: 0.0.0.0:1514 # the address and port to listen for syslog messages
      idle_timeout: 60s # the timeout for idle connections
      label_structured_data: yes # whether to add structured data as labels
      labels: # static labels to add to every log entry
        job: "syslog"
        ver: "1.67"


# # thank you chatgpt!
#   - job_name: edge_router_syslog
#     syslog:
#       listen_address: 0.0.0.0:1514 # the address and port to listen for syslog messages
#       idle_timeout: 60s # the timeout for idle connections
#       label_structured_data: yes # whether to add structured data as labels
#       labels: # static labels to add to every log entry
#         job: "edge_router_syslog"
#         ver: "1.61"
#         __syslog_connection_ip_address:
#         __syslog_connection_hostname:
        
      


